version: "3.9"
services:
  mysql:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./dbfiles:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
  node:
    build: ./backend
    container_name: server
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/bem346/backend
    depends_on:
      mysql:
        condition: service_started
    stdin_open: true
    tty: true
  react:
    build: ./frontend
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/bem346/react
    stdin_open: true
    tty: true
